services:
  postgres:
    image: postgres:16
    container_name: auction-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - auction_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: auction-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - auction_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  auction_pgdata:
  auction_redisdata: